/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrophiesRouteImport } from './routes/trophies'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as RoutesNewRouteImport } from './routes/routes.new'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'

const TrophiesRoute = TrophiesRouteImport.update({
  id: '/trophies',
  path: '/trophies',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesNewRoute = RoutesNewRouteImport.update({
  id: '/routes/new',
  path: '/routes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/feed': typeof FeedRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/trophies': typeof TrophiesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/groups/': typeof GroupsIndexRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/feed': typeof FeedRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/trophies': typeof TrophiesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/groups': typeof GroupsIndexRoute
  '/routes': typeof RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/feed': typeof FeedRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/terms': typeof TermsRoute
  '/trophies': typeof TrophiesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/groups/': typeof GroupsIndexRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/challenges'
    | '/feed'
    | '/leaderboards'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/trophies'
    | '/groups/$groupId'
    | '/routes/$routeId'
    | '/routes/new'
    | '/groups/'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/challenges'
    | '/feed'
    | '/leaderboards'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/trophies'
    | '/groups/$groupId'
    | '/routes/$routeId'
    | '/routes/new'
    | '/groups'
    | '/routes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/challenges'
    | '/feed'
    | '/leaderboards'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/terms'
    | '/trophies'
    | '/groups/$groupId'
    | '/routes/$routeId'
    | '/routes/new'
    | '/groups/'
    | '/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  FeedRoute: typeof FeedRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TermsRoute: typeof TermsRoute
  TrophiesRoute: typeof TrophiesRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  RoutesNewRoute: typeof RoutesNewRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trophies': {
      id: '/trophies'
      path: '/trophies'
      fullPath: '/trophies'
      preLoaderRoute: typeof TrophiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/new': {
      id: '/routes/new'
      path: '/routes/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof RoutesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  FeedRoute: FeedRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TermsRoute: TermsRoute,
  TrophiesRoute: TrophiesRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  RoutesNewRoute: RoutesNewRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
