/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as RoutesNewRouteImport } from './routes/routes.new'
import { Route as RoutesRouteIdRouteImport } from './routes/routes.$routeId'

const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesNewRoute = RoutesNewRouteImport.update({
  id: '/routes/new',
  path: '/routes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRouteIdRoute = RoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes': typeof RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/routes/$routeId': typeof RoutesRouteIdRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/feed'
    | '/leaderboards'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/feed'
    | '/leaderboards'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/feed'
    | '/leaderboards'
    | '/routes/$routeId'
    | '/routes/new'
    | '/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  RoutesRouteIdRoute: typeof RoutesRouteIdRoute
  RoutesNewRoute: typeof RoutesNewRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/new': {
      id: '/routes/new'
      path: '/routes/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof RoutesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/$routeId': {
      id: '/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof RoutesRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  RoutesRouteIdRoute: RoutesRouteIdRoute,
  RoutesNewRoute: RoutesNewRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
